// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6kHtkW4ywf9h_EsSPmM_U164ClBsOnaI',
    appId: '1:608301772658:web:34fcf6695e960dc24e77eb',
    messagingSenderId: '608301772658',
    projectId: 'fir-flu-d77fb',
    authDomain: 'fir-flu-d77fb.firebaseapp.com',
    storageBucket: 'fir-flu-d77fb.firebasestorage.app',
    measurementId: 'G-R3JW24GVKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQBFKaae-zX9B7XOJ-GCicTJtML4BcHvE',
    appId: '1:608301772658:android:7917060efc8520f04e77eb',
    messagingSenderId: '608301772658',
    projectId: 'fir-flu-d77fb',
    storageBucket: 'fir-flu-d77fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXUTBbtEL0GZmCzrlNVLzWgVHOamDQajM',
    appId: '1:608301772658:ios:4bb933d8213c56d24e77eb',
    messagingSenderId: '608301772658',
    projectId: 'fir-flu-d77fb',
    storageBucket: 'fir-flu-d77fb.firebasestorage.app',
    iosBundleId: 'com.example.taskInt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXUTBbtEL0GZmCzrlNVLzWgVHOamDQajM',
    appId: '1:608301772658:ios:4bb933d8213c56d24e77eb',
    messagingSenderId: '608301772658',
    projectId: 'fir-flu-d77fb',
    storageBucket: 'fir-flu-d77fb.firebasestorage.app',
    iosBundleId: 'com.example.taskInt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6kHtkW4ywf9h_EsSPmM_U164ClBsOnaI',
    appId: '1:608301772658:web:a51e190051dd19c34e77eb',
    messagingSenderId: '608301772658',
    projectId: 'fir-flu-d77fb',
    authDomain: 'fir-flu-d77fb.firebaseapp.com',
    storageBucket: 'fir-flu-d77fb.firebasestorage.app',
    measurementId: 'G-WYKDS7FB27',
  );
}
